### ISSUE TITLE
Clear Browser History/Cache etc.

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#41]
From a tester:
there's no "Clear Browser History/Cache etc.." right now, that should be a priority.. I browsed a bunch of websites and wanted to clear it so Brave was in a "Clean" state and can't without uninstalling/installing

**Comment by axelhuizinga** [comment]
simple workaround for now - close brave - empty C:\Users\<username>\AppData\Roaming\brave\Cache - restart

**Comment by jamesacampbell** [comment]
in case you are on OSX, the workaround is to empty the Application Support folder:
`cd ~/Library/Application Support/Brave/Cache/` then `rm -rf *`

**Comment by garvankeeley** [comment]
fixed in 1.0

**Comment by dandart** [comment]
On latest 0.11.5, it's rm -rf ~/.config/brave/Cache/*
Not sure where 1.0 comes in - is that some kind of beta?

**Comment by dandart** [comment]
Hang on - I think OP meant iOS...

**Comment by firstworldengineer** [comment]
This is marked as closed but iOS still doesn't have this feature. Can we re open it?
