### ISSUE TITLE
Bookmark title becomes misaligned when editing

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#833]
Description:
When editing a bookmark, the title gets pushed to the left and doesn't return.
If the bookmark name is too long, it overflows the controls.

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Bookmark titles should not hang out to the left when a user is done editing nor should they overflow to the right.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6s+

- Brave Version:
1.3.2 (17.04.19.16)

- Steps to reproduce:
    1. Set some bookmarks.
    2. Enter edit mode.
    3. Select a bookmark.
    4. Select none.

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:
![image1](https://cloud.githubusercontent.com/assets/1434040/25256147/463e024e-25f4-11e7-9f17-53a77d77666b.PNG)

![image uploaded from ios 6](https://cloud.githubusercontent.com/assets/1434040/25256881/b4f307d4-25f9-11e7-8803-e52dddd4b088.jpg)

- Any related issues:

**Comment by alexwykoff** [comment]
this doesn't appear to have worked for me

[2017-04-28 16-29-46.mp4.zip](https://github.com/brave/browser-ios/files/965605/2017-04-28.16-29-46.mp4.zip)

**Comment by jhreis** [comment]
Broken commit via bisect: 0eca80209e24c9fed1e7a20d6ae1aceea80521ad

**Comment by iccub** [comment]
Cannot reproduce.
It should work now. Currently you can't enter edit mode and swipe to show 'edit' menu at the same time.

**Comment by jhreis** [comment]
Forgot to mention here, this works completely fine in iOS11 for some odd reason. Still repro on older OS's, probably a non-fix but will leave open at least until iOS9-10 support is dropped.

**Comment by srirambv** [comment]
Looks fixed 1.6.2(18.05.29.10) on iOS 11.4.

**Comment by jhreis** [comment]
Adding to next release so we can run a pass on it before release.

**Comment by kjozwiak** [comment]
Looks like this is still happening but isn't as bad as before. When you're editing the bookmarks, you'll notice that cancelling the edit for an individual bookmarks will push the title to the left and leave a single letter remaining. If you edit the same bookmark and cancel for the second time, that single letter from the title will be moved to the left and sometimes appear under the red `-` button.

STR (example of the issue: https://youtu.be/NmsTrUwaMyU):

1. add a few bookmarks (I added 4)
2. go into edit mode by taping on the pencil/pen
3. tap on the red left button for a bookmark so you see the `Edit` & `Delete` options on the right hand side
4. click on another bookmark to cancel the edit.. You'll notice that only the first letter of the title remains
5. repeat the same thing on the same bookmark and you'll notice that the remaining text (single letter) is moved to the left underneath the red edit button before it disappears
